### ISSUE TITLE
openBMC is not building for SP5 machine. 

### ISSUE THREAD

**Issue by jdhanasekar** [AMDESE/OpenBMC#6]
Hi AMD,

I am getting build error when I built ```AMDESE/openBMC``` (master branch) .
I have followed the instruction mentioned in this site https://github.com/AMDESE/OpenBMC.
**Note on Bugs**
Please note that questions or feature requests should be discussed on the
mailing list or Discord. Please see https://github.com/openbmc/openbmc#contact
for info on how to contact us. Github Issues in openbmc/openbmc are for bugs
only. Please remove this section when opening a bug.

**Unexpected behavior**
WARNING: /home/user/dhanasekar/BMC/AMD/AMDESE/OB1/OpenBMC/meta-amd/meta-common/recipes-amd/power-capping/power-capping.bb: Exception during build_dependencies for AUTOREV
WARNING: /home/user/dhanasekar/BMC/AMD/AMDESE/OB1/OpenBMC/meta-amd/meta-common/recipes-amd/power-capping/power-capping.bb: Error during finalise of /home/user/dhanasekar/BMC/AMD/AMDESE/OB1/OpenBMC/meta-amd/meta-common/recipes-amd/power-capping/power-capping.bb
ERROR: ExpansionError during parsing /home/user/dhanasekar/BMC/AMD/AMDESE/OB1/OpenBMC/meta-amd/meta-common/recipes-amd/power-capping/power-capping.bb
Traceback (most recent call last):
  File "/home/user/dhanasekar/BMC/AMD/AMDESE/OB1/OpenBMC/poky/bitbake/lib/bb/fetch2/__init__.py", line 1172, in srcrev_internal_helper(ud=<bb.fetch2.FetchData object at 0x7f47acac06a0>, d=<bb.data_smart.DataSmart object at 0x7f47ab4ae5b0>, name='default'):
         if srcrev == "AUTOINC":
    >        srcrev = ud.method.latest_revision(ud, d, name)
     
  File "/home/user/dhanasekar/BMC/AMD/AMDESE/OB1/OpenBMC/poky/bitbake/lib/bb/fetch2/__init__.py", line 1581, in Git.latest_revision(ud=<bb.fetch2.FetchData object at 0x7f47acac06a0>, d=<bb.data_smart.DataSmart object at 0x7f47ab4ae5b0>, name='default'):
             except KeyError:
    >            revs[key] = rev = self._latest_revision(ud, d, name)
                 return rev
  File "/home/user/dhanasekar/BMC/AMD/AMDESE/OB1/OpenBMC/poky/bitbake/lib/bb/fetch2/git.py", line 690, in Git._latest_revision(ud=<bb.fetch2.FetchData object at 0x7f47acac06a0>, d=<bb.data_smart.DataSmart object at 0x7f47ab4ae5b0>, name='default'):
             """
    >        output = self._lsremote(ud, d, "")
             # Tags of the form ^{} may not work, need to fallback to other form
  File "/home/user/dhanasekar/BMC/AMD/AMDESE/OB1/OpenBMC/poky/bitbake/lib/bb/fetch2/git.py", line 679, in Git._lsremote(ud=<bb.fetch2.FetchData object at 0x7f47acac06a0>, d=<bb.data_smart.DataSmart object at 0x7f47ab4ae5b0>, search=''):
                     bb.fetch2.check_network_access(d, cmd, repourl)
    >            output = runfetchcmd(cmd, d, True)
                 if not output:
  File "/home/user/dhanasekar/BMC/AMD/AMDESE/OB1/OpenBMC/poky/bitbake/lib/bb/fetch2/__init__.py", line 889, in runfetchcmd(cmd='export PSEUDO_DISABLED=1; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus,guid=81ff6b66be9365dac7f1b79d64c0db4f"; export SSH_AGENT_PID="13332"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/user/dhanasekar/BMC/AMD/AMDESE/OB1/OpenBMC/scripts:/home/user/dhanasekar/BMC/AMD/AMDESE/OB1/OpenBMC/build/sp5/tmp/work/armv7ahf-vfpv4d16-openbmc-linux-gnueabi/power-capping/1.0-r0/recipe-sysroot-native/usr/bin/arm-openbmc-linux-gnueabi:/home/user/dhanasekar/BMC/AMD/AMDESE/OB1/OpenBMC/build/sp5/tmp/work/armv7ahf-vfpv4d16-openbmc-linux-gnueabi/power-capping/1.0-r0/recipe-sysroot/usr/bin/crossscripts:/home/user/dhanasekar/BMC/AMD/AMDESE/OB1/OpenBMC/build/sp5/tmp/work/armv7ahf-vfpv4d16-openbmc-linux-gnueabi/power-capping/1.0-r0/recipe-sysroot-native/usr/sbin:/home/user/dhanasekar/BMC/AMD/AMDESE/OB1/OpenBMC/build/sp5/tmp/work/armv7ahf-vfpv4d16-openbmc-linux-gnueabi/power-capping/1.0-r0/recipe-sysroot-native/usr/bin:/home/user/dhanasekar/BMC/AMD/AMDESE/OB1/OpenBMC/build/sp5/tmp/work/armv7ahf-vfpv4d16-openbmc-linux-gnueabi/power-capping/1.0-r0/recipe-sysroot-native/sbin:/home/user/dhanasekar/BMC/AMD/AMDESE/OB1/OpenBMC/build/sp5/tmp/work/armv7ahf-vfpv4d16-openbmc-linux-gnueabi/power-capping/1.0-r0/recipe-sysroot-native/bin:/home/user/dhanasekar/BMC/AMD/AMDESE/OB1/OpenBMC/poky/bitbake/bin:/home/user/dhanasekar/BMC/AMD/AMDESE/OB1/OpenBMC/build/sp5/tmp/hosttools"; export HOME="/home/user"; git -c core.fsyncobjectfiles=0 ls-remote ssh://git@github.com/AMDESE/amd-power-cap.git ', d=<bb.data_smart.DataSmart object at 0x7f47ab4ae5b0>, quiet=True, cleanup=[], log=None, workdir=None):
     
    >        raise FetchError(error_message)
     
bb.data_smart.ExpansionError: Failure expanding variable SRCPV, expression was ${@bb.fetch2.get_srcrev(d)} which triggered exception FetchError: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus,guid=81ff6b66be9365dac7f1b79d64c0db4f"; export SSH_AGENT_PID="13332"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/user/dhanasekar/BMC/AMD/AMDESE/OB1/OpenBMC/scripts:/home/user/dhanasekar/BMC/AMD/AMDESE/OB1/OpenBMC/build/sp5/tmp/work/armv7ahf-vfpv4d16-openbmc-linux-gnueabi/power-capping/1.0-r0/recipe-sysroot-native/usr/bin/arm-openbmc-linux-gnueabi:/home/user/dhanasekar/BMC/AMD/AMDESE/OB1/OpenBMC/build/sp5/tmp/work/armv7ahf-vfpv4d16-openbmc-linux-gnueabi/power-capping/1.0-r0/recipe-sysroot/usr/bin/crossscripts:/home/user/dhanasekar/BMC/AMD/AMDESE/OB1/OpenBMC/build/sp5/tmp/work/armv7ahf-vfpv4d16-openbmc-linux-gnueabi/power-capping/1.0-r0/recipe-sysroot-native/usr/sbin:/home/user/dhanasekar/BMC/AMD/AMDESE/OB1/OpenBMC/build/sp5/tmp/work/armv7ahf-vfpv4d16-openbmc-linux-gnueabi/power-capping/1.0-r0/recipe-sysroot-native/usr/bin:/home/user/dhanasekar/BMC/AMD/AMDESE/OB1/OpenBMC/build/sp5/tmp/work/armv7ahf-vfpv4d16-openbmc-linux-gnueabi/power-capping/1.0-r0/recipe-sysroot-native/sbin:/home/user/dhanasekar/BMC/AMD/AMDESE/OB1/OpenBMC/build/sp5/tmp/work/armv7ahf-vfpv4d16-openbmc-linux-gnueabi/power-capping/1.0-r0/recipe-sysroot-native/bin:/home/user/dhanasekar/BMC/AMD/AMDESE/OB1/OpenBMC/poky/bitbake/bin:/home/user/dhanasekar/BMC/AMD/AMDESE/OB1/OpenBMC/build/sp5/tmp/hosttools"; export HOME="/home/user"; git -c core.fsyncobjectfiles=0 ls-remote ssh://git@github.com/AMDESE/amd-power-cap.git  failed with exit code 1, output:
Traceback (most recent call last):
  File "/home/user/dhanasekar/BMC/AMD/AMDESE/OB1/OpenBMC/build/sp5/tmp/hosttools/git", line 30, in <module>
    os.execv(real_git, sys.argv)
TypeError: execv: path should be string, bytes or os.PathLike, not NoneType

Summary: There were 3 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
user@quanta:~/dhanasekar/BMC/AMD/AMDESE/OB1/OpenBMC/build/sp5$ 

A clear and concise description of what unexpectedly happened.

**Expected behavior**
Source should build successfully for sp5 machine.

**To Reproduce**
1. In Ubuntu Terminal type,  ``mkdir OpenBMC``
2. ``cd OpenBMC``
3. ``git clone https://github.com/AMDESE/OpenBMC.git .``
4. ``. setup sp5``
5. ``bitbake obmc-phosphor-image``

**Screenshots**

![image](https://github.com/AMDESE/OpenBMC/assets/51257095/db330125-e351-4e5a-8b53-66b0ce99dbc8)

**OS Information:**
 - /etc/os-release:
``NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic``

 - uname -a:
  ``Linux quanta 4.15.0-176-generic #185-Ubuntu SMP Tue Mar 29 17:40:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux``

Please correct me, If I made any mistake in building process. 
Please provide your suggestion.

**Comment by supven01** [comment]
Problem may be related to git installation. Please re-check your git installation and give it a try.

**Comment by garybeihl** [comment]
I see this issue also with git version 2.17.1 - was there ever a resolution for it?

**Comment by supven01** [comment]
> I see this issue also with git version 2.17.1 - was there ever a resolution for it?

Its root caused to configuration of the system that is being used to build.
However, work around is to replace AUTOREV keyword in the recipe files with the actual revision.

**Comment by garybeihl** [comment]
Thank you for your reply – could you please explain this in a little more detail? An actual example would be very helpful. Do all the .bb recipe files need to be updated? Or is there a way to adjust my configuration so that it is correct? I am running Ubuntu 18.04 in a VM if that makes any difference…

**Comment by garybeihl** [comment]
Never mind - I think I got it - I just substituted the latest SHA commit hash for the failing recipe files and it seems to be doing better now. Thanks!
